
import __ASTRO_IMAGE_IMPORT_1gjNiL from "../../assets/posts/17-de-septiembre-la-partida-de-mi-viejo-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F17-de-septiembre-la-partida-de-mi-viejo.md";
import __ASTRO_IMAGE_IMPORT_Z21YSaP from "../../assets/posts/alergia-al-wifi-electrosensibilidad-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Falergia-al-wifi-electrosensibilidad.md";
import __ASTRO_IMAGE_IMPORT_ZxER2u from "../../assets/posts/comprender-la-fragilidad-de-quien-amamos-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcomprender-la-fragilidad-de-quien-amamos.md";
import __ASTRO_IMAGE_IMPORT_YNlOS from "../../assets/posts/halloween-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhalloween.md";
import __ASTRO_IMAGE_IMPORT_2dtzb2 from "../../assets/posts/mis-aprendizajes-y-el-asperger-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmis-aprendizajes-y-el-asperger.md";
import __ASTRO_IMAGE_IMPORT_H3Ykq from "../../assets/posts/que-es-gtd-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fque-es-gtd.md";
import __ASTRO_IMAGE_IMPORT_2pnYys from "../../assets/posts/que-es-y-como-funciona-zen-to-done-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fque-es-y-como-funciona-zen-to-done.md";
import __ASTRO_IMAGE_IMPORT_LOUz from "../../assets/posts/sueno-polifasico-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsueno-polifasico.md";
export default new Map([["../../assets/posts/17-de-septiembre-la-partida-de-mi-viejo-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F17-de-septiembre-la-partida-de-mi-viejo.md", __ASTRO_IMAGE_IMPORT_1gjNiL], ["../../assets/posts/alergia-al-wifi-electrosensibilidad-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Falergia-al-wifi-electrosensibilidad.md", __ASTRO_IMAGE_IMPORT_Z21YSaP], ["../../assets/posts/comprender-la-fragilidad-de-quien-amamos-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcomprender-la-fragilidad-de-quien-amamos.md", __ASTRO_IMAGE_IMPORT_ZxER2u], ["../../assets/posts/halloween-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhalloween.md", __ASTRO_IMAGE_IMPORT_YNlOS], ["../../assets/posts/mis-aprendizajes-y-el-asperger-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmis-aprendizajes-y-el-asperger.md", __ASTRO_IMAGE_IMPORT_2dtzb2], ["../../assets/posts/que-es-gtd-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fque-es-gtd.md", __ASTRO_IMAGE_IMPORT_H3Ykq], ["../../assets/posts/que-es-y-como-funciona-zen-to-done-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fque-es-y-como-funciona-zen-to-done.md", __ASTRO_IMAGE_IMPORT_2pnYys], ["../../assets/posts/sueno-polifasico-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsueno-polifasico.md", __ASTRO_IMAGE_IMPORT_LOUz]]);
		